Add devise
maaloum/Blog_Rails pull request #9
Opened 2023-04-13 15:04 UTC by maaloum

In this PR, I : 

- [ ] Removed the current_user method in ApplicationController.
- [ ]     [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
- [ ]         Can register a new user.
- [ ]         User logs in with a combination of email and password.
- [ ]         Hashed password should be stored in the database.
- [ ]         Ask for confirmation of email.
- [ ]         Can reset password.
- [ ]     Modified the views in devise for registration and login to match the wireframes from the Sneak Peek

2023-04-13 16:04 UTC, Gambit142 requested changes
Hi @maaloum @harshitajain06 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- README.md file is professional ✔️ 
- Use of devise gem for user's authentication ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-04-13 16:04 UTC, Gambit142 commented on app/controllers/users_controller.rb
>    end
- [ ] In the application controller, kindly remove the `current_user` method that returns the first user object in the application. Devise automatically provides the current user details of the person that is logged in. 👍 😎

2023-04-13 16:04 UTC, Gambit142 commented on db/migrate/20230413140233_add_devise_to_users.rb
> +  def change
- [ ] When I run the migrations in this directory, I get this error:

![image](https://user-images.githubusercontent.com/77106962/231809942-528dd466-6faf-414c-92af-dec1c59fb52c.png)

#### To resolve this, kindly change the name of this class to `AddDeviseToUser` from `DeviseCreateUsers`. Remember that good rails logic uses convention rather than configuration. The name of classes in migration files usually follows the name of the migration file itself. For example, if your migration file is called 
`20210213040840_add_first_initial_only_to_users.rb`, then the class name in your migration file should be
`AddFirstInitialOnlyToUsers`. Kindly correct the name. 👍 😎

2023-04-13 16:04 UTC, Gambit142 commented on db/migrate/20230413140233_add_devise_to_users.rb
> +      ## Database authenticatable
- [ ] Kindly change this line of code to `change_table :users do |t|` because the `users` table already exists. The devise gem would be changing the `users` table by adding some columns to it. 👍 😎

2023-04-13 16:04 UTC, Gambit142 commented on db/migrate/20230413140233_add_devise_to_users.rb
> +    end
- [ ] Kindly remove this line of code because this column exists in the `users` table. Remember that the `t.timestamps` create the `created_at` and `updated_at` columns in the `users` table. 💻

2023-04-13 16:04 UTC, Gambit142 commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] Kindly activate the `:confirmable` module of `devise.` The `:confirmable` module enables the application to confirm users' email when they sign up or create an account. Kindly activate it.

#### Hint: Uncomment the `:confirmable` attribute in the `app/models/user.rb` file and then uncomment the `confirmable` columns in the migration file that adds `devise` to users in the migration directory. 👍 😎

2023-04-13 16:04 UTC, Gambit142 commented on app/views/devise/registrations/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] When I try to sign up or create an account, I get the following error:

![image](https://user-images.githubusercontent.com/77106962/231816319-25784d66-02fb-4939-b9d9-edfd43292b7b.png)

#### To resolve this, you need to add a form input for the name attribute for the user. Kindly implement this feature. 👍 😎

2023-04-13 16:04 UTC, Gambit142 commented on app/views/devise/sessions/new.html.erb
> +
- [ ] Kindly modify and style the signup page and log-in page to look identical to that of the wireframe provided for this project. 👍  

### Your Design (Signup Page)

![image](https://user-images.githubusercontent.com/77106962/231817510-0f471ef6-a1b9-43e2-9037-de83c97e04bd.png)

### Your Design (Login Page)

![image](https://user-images.githubusercontent.com/77106962/231817690-27d6d8ba-9709-4fac-b634-48aa825f1eca.png)

### Wireframe Provided
![image](https://user-images.githubusercontent.com/77106962/231817880-aba1e3c7-7815-410e-9070-54a6b653dadc.png)

#### Hint: You can leave the extra links like the `Forgot Password Links` and the rest but style the form inputs to look identical to that of he wireframe. 👍 😎

2023-04-14 12:05 UTC, mwanawabangona approved these changes
Hi @maaloum,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 12:11 UTC, merged